Repository gudtldn/Week2-Engine, pull requests merged in 2025-03, with the labels that each got.

#1 Add index data
  Source/Core/Math/Matrix.cpp
  Source/Core/Rendering/BufferCache.cpp
  Source/Core/Rendering/BufferCache.h
  Source/Core/Rendering/URenderer.cpp
  Source/Core/Rendering/URenderer.h
  Source/Object/Actor/Quad.cpp
  Source/Object/Actor/Quad.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.h
  Source/Primitive/PrimitiveVertices.cpp
  Source/Primitive/PrimitiveVertices.h
  Source/Primitive/UGeometryGenerator.cpp
  Source/Primitive/UGeometryGenerator.h
  t0.vcxproj.filters
Labels: size/XXL

#8 Add atlas class
  Shaders/Font_PS.hlsl
  Shaders/Font_VS.hlsl
  Shaders/ShaderW0.hlsl
  Source/Core/Rendering/BufferCache.cpp
  Source/Core/Rendering/URenderer.cpp
  Source/Core/Rendering/URenderer.h
  Source/Object/Actor/Quad.cpp
  Source/Object/PrimitiveComponent/UPrimitiveComponent.h
  Source/Primitive/PrimitiveVertices.h
  Source/UFontAtlas.cpp
  Source/UFontAtlas.h
  font_atlas.png
  t0.vcxproj
  t0.vcxproj.filters
Labels: size/L

#9 feat/Resource
  Config/editor.ini
  Source/Core/Engine.cpp
  Source/Core/Rendering/BufferCache.cpp
  Source/Core/Rendering/BufferCache.h
  Source/Core/Rendering/URenderer.cpp
  Source/Core/Rendering/URenderer.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.cpp
  Source/Object/PrimitiveComponent/UPrimitiveComponent.h
  Source/Resource/DirectResource/DirectBuffer.cpp
  Source/Resource/DirectResource/DirectBuffer.h
  Source/Resource/DirectResource/IndexBuffer.cpp
  Source/Resource/DirectResource/IndexBuffer.h
  Source/Resource/DirectResource/Vertexbuffer.cpp
  Source/Resource/DirectResource/Vertexbuffer.h
  Source/Resource/RenderResourceManager.cpp
  Source/Resource/RenderResourceManager.h
  Source/Resource/Resource.cpp
  Source/Resource/Resource.h
  imgui.ini
  t0.vcxproj
Labels: size/XXL

#11 feat/Resource2
  Config/editor.ini
  Shaders/ShaderW0.hlsl
  Source/Core/Engine.cpp
  Source/Core/Engine.h
  Source/Core/Rendering/FDevice.cpp
  Source/Core/Rendering/FDevice.h
  Source/Core/Rendering/FDeviceResource.cpp
  Source/Core/Rendering/UI.cpp
  Source/Core/Rendering/UI.h
  Source/Core/Rendering/URenderer.cpp
  Source/Core/Rendering/URenderer.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.cpp
  Source/Object/PrimitiveComponent/UPrimitiveComponent.h
  Source/Object/World/World.cpp
  Source/Resource/DirectResource/DirectBuffer.cpp
  Source/Resource/DirectResource/IndexBuffer.cpp
  Source/Resource/DirectResource/IndexBuffer.h
  Source/Resource/DirectResource/InputLayout.cpp
  Source/Resource/DirectResource/InputLayout.h
  Source/Resource/DirectResource/PixelShader.cpp
  Source/Resource/DirectResource/PixelShader.h
  Source/Resource/DirectResource/Shader.cpp
  Source/Resource/DirectResource/Shader.h
  Source/Resource/DirectResource/VertexShader.cpp
  Source/Resource/DirectResource/VertexShader.h
  Source/Resource/DirectResource/Vertexbuffer.cpp
  Source/Resource/DirectResource/Vertexbuffer.h
  Source/Resource/Resource.h
  Source/Static/FLineBatchManager.cpp
  imgui.ini
  main.cpp
  t0.vcxproj
  t0.vcxproj.filters
Labels: size/XXL

#10 Test/ray test
  Source/Core/Engine.cpp
  Source/Core/Engine.h
  Source/Core/Input/PlayerController.cpp
  Source/Core/Input/PlayerInput.cpp
  Source/Core/Input/PlayerInput.h
  Source/Core/Math/MathUtility.h
  Source/Core/Math/Matrix.cpp
  Source/Core/Math/Matrix.h
  Source/Core/Math/Quat.cpp
  Source/Core/Math/Quat.h
  Source/Core/Math/Ray.cpp
  Source/Core/Math/Ray.h
  Source/Core/Math/Rotator.cpp
  Source/Core/Math/Rotator.h
  Source/Core/Math/Transform.h
  Source/Core/Math/Vector.cpp
  Source/Core/Math/Vector.h
  Source/Core/Rendering/URenderer.cpp
  Source/Core/Rendering/URenderer.h
  Source/Object/Actor/Actor.h
  Source/Object/Actor/Camera.cpp
  Source/Object/Actor/Camera.h
  Source/Object/ActorComponent/ActorComponent.cpp
  Source/Object/ActorComponent/ActorComponent.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.h
  Source/Object/World/World.cpp
  Source/Object/World/World.h
  Source/ThirdParty/ImGui/include/ImGui/imconfig.h
  imgui.ini
  t0.vcxproj
  t0.vcxproj.filters
Labels: size/XXL

#13 update billboard text quad
  Shaders/Font_PS.hlsl
  Shaders/Font_VS.hlsl
  Source/FontAtlas.h
  Source/Object/Actor/Picker.cpp
  Source/Primitive/PrimitiveVertices.h
  Source/Static/FUUIDBillBoard.cpp
  Source/Static/FUUIDBillBoard.h
  t0.vcxproj
  t0.vcxproj.filters
Labels: size/L

#14 Feature/rtti
  Source/Core/AbstractClass/Singleton.h
  Source/Core/Config/ConfigManager.cpp
  Source/Core/Config/ConfigManager.h
  Source/Core/Container/String.cpp
  Source/Core/Container/String.h
  Source/Core/HAL/PlatformType.h
  Source/Core/Rendering/URenderer.cpp
  Source/Core/UObject/Casts.cpp
  Source/Core/UObject/Casts.h
  Source/Core/UObject/Class.cpp
  Source/Core/UObject/Class.h
  Source/Core/UObject/Object.cpp
  Source/Core/UObject/Object.h
  Source/Core/UObject/ObjectMacros.h
  Source/Object/Actor/Actor.h
  Source/Object/Actor/Arrow.h
  Source/Object/Actor/Camera.h
  Source/Object/Actor/Cone.h
  Source/Object/Actor/Cube.h
  Source/Object/Actor/Cylinder.h
  Source/Object/Actor/Picker.h
  Source/Object/Actor/Quad.h
  Source/Object/Actor/Sphere.h
  Source/Object/ActorComponent/ActorComponent.h
  Source/Object/Assets/Asset.h
  Source/Object/Assets/AssetManager.h
  Source/Object/Assets/SceneAsset.h
  Source/Object/Gizmo/Axis.h
  Source/Object/Gizmo/GizmoHandle.h
  Source/Object/ObjectFactory.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.h
  Source/Object/USceneComponent.h
  Source/Object/World/World.h
  Source/Static/FUUIDBillBoard.cpp
  t0.vcxproj
Labels: size/L

#15 Resolve renderer merge conflice
  Source/Core/Rendering/URenderer.cpp
  Source/Core/Rendering/URenderer.h
Labels: size/L

#16 Feature/guizmo
  Source/Core/Input/PlayerController.cpp
  Source/Core/Math/BoxSphereBounds.cpp
  Source/Core/Math/BoxSphereBounds.h
  Source/Core/Math/Matrix.cpp
  Source/Core/Math/Matrix.h
  Source/Core/Math/Quat.cpp
  Source/Core/Math/Quat.h
  Source/Core/Math/Ray.cpp
  Source/Core/Math/Ray.h
  Source/Core/Math/Transform.h
  Source/Core/Math/Vector.cpp
  Source/Core/Math/Vector.h
  Source/Core/Rendering/FDeviceResource.cpp
  Source/Core/Rendering/UI.cpp
  Source/Core/Rendering/URenderer.cpp
  Source/Core/UObject/Object.h
  Source/Object/Actor/Actor.cpp
  Source/Object/Actor/Actor.h
  Source/Object/Actor/Camera.cpp
  Source/Object/Actor/Cylinder.cpp
  Source/Object/Actor/Picker.cpp
  Source/Object/ActorComponent/ActorComponent.cpp
  Source/Object/ActorComponent/ActorComponent.h
  Source/Object/Gizmo/Axis.cpp
  Source/Object/Gizmo/GizmoActor.cpp
  Source/Object/Gizmo/GizmoActor.h
  Source/Object/Gizmo/GizmoHandle.cpp
  Source/Object/Gizmo/GizmoHandle.h
  Source/Object/USceneComponent.cpp
  Source/Object/USceneComponent.h
  Source/Object/World/World.cpp
  Source/Object/World/World.h
  Source/Resource/DirectResource/PixelShader.cpp
  Source/Resource/DirectResource/VertexShader.cpp
  Source/Static/FEditorManager.cpp
  Source/Static/FEditorManager.h
  imgui.ini
  t0.vcxproj
  t0.vcxproj.filters
Labels: size/XXL

#17 ISSUE : 컴포넌트 자식 회전이 제대로 안됨
  Source/Core/Math/Quat.cpp
  Source/Core/Math/Quat.h
  Source/Core/Math/Transform.h
  Source/Core/Math/Vector.h
  Source/Object/Actor/Actor.cpp
  Source/Object/Actor/Actor.h
  Source/Object/Actor/Cylinder.cpp
  Source/Object/USceneComponent.cpp
  Source/Object/USceneComponent.h
Labels: size/L

#18 Update UUID billboard functions
  Shaders/Font_VS.hlsl
  Source/Core/Rendering/URenderer.cpp
  Source/Object/World/World.cpp
  Source/Static/FUUIDBillBoard.cpp
  Source/Static/FUUIDBillBoard.h
Labels: size/M

#19 Add showflags
  Source/Core/Rendering/UI.cpp
  Source/Core/Rendering/UI.h
  Source/Debug/EngineShowFlags.cpp
  Source/Debug/EngineShowFlags.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.cpp
  Source/Static/FUUIDBillBoard.cpp
  Source/Static/FUUIDBillBoard.h
  t0.vcxproj
Labels: size/L

#20 add viewmode feature
  Source/Core/Rendering/FViewMode.cpp
  Source/Core/Rendering/FViewMode.h
  Source/Core/Rendering/UI.cpp
  Source/Core/Rendering/UI.h
  Source/Core/Rendering/URenderer.cpp
  Source/Core/Rendering/URenderer.h
  Source/Static/FUUIDBillBoard.cpp
  t0.vcxproj
Labels: size/L

#21 change logic - get atlas data from file
  Source/FontAtlas.cpp
  Source/FontAtlas.h
  Source/Static/FUUIDBillBoard.cpp
  font_atlas.txt
Labels: size/L

#22 add compositional hangeul render
  Pretendard_Kor.png
  Pretendard_Kor.txt
  Source/Core/Rendering/URenderer.cpp
  Source/FontAtlas.cpp
  Source/Static/FUUIDBillBoard.cpp
  Source/Static/FUUIDBillBoard.h
Labels: size/L

#23 Feature/transform
  Source/Core/Math/Transform.h
  Source/Object/Actor/Cylinder.cpp
  imgui.ini
Labels: size/M

#24 Refactor/remove_pixel_picking
  Source/Core/Engine.cpp
  Source/Object/World/World.cpp
Labels: size/XS

#25 wip : GizmoComponent 구조 짜놓고 진행 중, std::string FString 기반으로 수정
  Config/editor.ini
  Source/Core/Config/ConfigManager.cpp
  Source/Core/Config/ConfigManager.h
  Source/Core/Container/String.h
  Source/Core/Engine.cpp
  Source/Core/Engine.h
  Source/Object/Actor/Camera.cpp
  Source/Object/Assets/Asset.h
  Source/Object/Assets/AssetManager.cpp
  Source/Object/Assets/AssetManager.h
  Source/Object/Assets/MeshAsset.cpp
  Source/Object/Assets/MeshAsset.h
  Source/Object/Assets/SceneAsset.cpp
  Source/Object/Assets/SceneAsset.h
  Source/Object/Gizmo/GizmoActor.cpp
  Source/Object/Gizmo/GizmoActor.h
  Source/Object/PrimitiveComponent/GizmoComponent.cpp
  Source/Object/PrimitiveComponent/GizmoComponent.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.cpp
  Source/Object/PrimitiveComponent/UPrimitiveComponent.h
  Source/Primitive/PrimitiveVertices.h
  cpp.hint
  imgui.ini
  main.cpp
  t0.vcxproj
  t0.vcxproj.filters
Labels: size/XL

#27 Feature/pixel picking
  Config/editor.ini
  Source/Core/Container/String.cpp
  Source/Core/Container/String.h
  Source/Core/Engine.cpp
  Source/Core/Rendering/UI.cpp
  Source/Core/Rendering/UI.h
  Source/Object/Actor/Actor.cpp
  Source/Object/ActorComponent/ActorComponent.cpp
  Source/Object/ActorComponent/ActorComponent.h
  Source/Object/World/World.cpp
  Source/Object/World/World.h
  imgui.ini
  main.cpp
Labels: size/L

#28 feat : Orthographic Camera 구현 및 Orthographic에서 마우스 휠로 ZoomIn, ZoomOut
  Config/editor.ini
  Source/Core/Engine.cpp
  Source/Core/Math/Matrix.h
  Source/Object/Actor/Camera.cpp
  Source/Object/Actor/Camera.h
Labels: size/M

#26 Feature/delegate
  Source/Core/Delegates/Delegate.h
  Source/Core/Delegates/DelegateCombination.h
  Source/Primitive/PrimitiveVertices.cpp
  Source/Primitive/PrimitiveVertices.h
  t0.vcxproj
Labels: size/XXL

#29 Feature/pixel picking
  Shaders/ShaderW0.hlsl
  Source/Core/Rendering/FDeviceResource.cpp
  Source/Object/Gizmo/GizmoActor.cpp
  Source/Object/PrimitiveComponent/GizmoComponent.cpp
  Source/Object/PrimitiveComponent/UPrimitiveComponent.cpp
  Source/Resource/Material.cpp
  Source/Resource/RenderResourceCollection.cpp
  Source/Resource/RenderResourceCollection.h
  WorldGrid.cpp
  WorldGrid.h
  imgui.ini
  t0.vcxproj
  t0.vcxproj.filters
Labels: size/L

#31 BoundBox 계산 Update마다 하는 거로 넣어놨습니다.
  Source/Core/Math/BoxSphereBounds.cpp
  Source/Core/Math/BoxSphereBounds.h
  Source/Core/Math/Transform.cpp
  Source/Core/Math/Transform.h
  Source/Core/Math/Vector.h
  Source/Debug/UDebugDrawManager.cpp
  Source/Debug/UDebugDrawManager.h
  Source/Object/Actor/Actor.cpp
  Source/Object/Actor/Actor.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.cpp
  Source/Object/PrimitiveComponent/UPrimitiveComponent.h
  Source/Object/USceneComponent.cpp
  Source/Object/USceneComponent.h
  Source/Object/World/World.cpp
  Source/Resource/DirectResource/Vertexbuffer.cpp
  Source/Resource/DirectResource/Vertexbuffer.h
  Source/Resource/RenderResourceCollection.h
  imgui.ini
  t0.vcxproj
  t0.vcxproj.filters
Labels: size/XL

#33 Fix/world_save_memleak
  Source/Core/EngineStatics.h
  Source/Core/Interfaces/GizmoInterface.h
  Source/Core/Utils/JsonSaveHelper.cpp
  Source/Core/Utils/JsonSaveHelper.h
  Source/Object/Actor/Actor.h
  Source/Object/Actor/Camera.cpp
  Source/Object/Actor/Camera.h
  Source/Object/Actor/Picker.cpp
  Source/Object/Actor/Picker.h
  Source/Object/Gizmo/Axis.cpp
  Source/Object/Gizmo/Axis.h
  Source/Object/Gizmo/GizmoActor.cpp
  Source/Object/Gizmo/GizmoActor.h
  Source/Object/Gizmo/GizmoHandle.cpp
  Source/Object/Gizmo/GizmoHandle.h
  Source/Object/PrimitiveComponent/UPrimitiveComponent.cpp
  Source/Object/World/World.cpp
  t0.vcxproj
Labels: size/L

#35 add-spot-light
  Source/Core/Engine.cpp
  Source/Core/Rendering/UI.cpp
  Source/Object/Actor/SpotLight.cpp
  Source/Object/Actor/SpotLight.h
  Source/Object/Light/LightComponent.cpp
  Source/Object/Light/LightComponent.h
  Source/Object/Light/LightComponentBase.cpp
  Source/Object/Light/LightComponentBase.h
  Source/Object/Light/SpotLightComponent.cpp
  Source/Object/Light/SpotLightComponent.h
  Source/Object/World/World.cpp
  t0.vcxproj
Labels: size/XL

#37 fix : BoundBox 이동 수정
  Config/editor.ini
  Source/Debug/DebugDrawManager.cpp
Labels: size/M
